# Generated by Django 5.1.4 on 2025-01-02 19:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100000, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')]),
        ),
    ]
